//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateMVC_NOAUTH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADMIN
    {
        public int ID { get; set; }

        [Display(Name = "Username")]
        [DataType(DataType.Text)]
        [StringLength(255, MinimumLength = 2)]
        public string USERNAME { get; set; }

        [Display(Name ="Password")]
        [DataType(DataType.Password)]
        [StringLength(255, MinimumLength = 2)]
        public string PASSWORD { get; set; }
    }
}
