//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateMVC_NOAUTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPERTY
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DESCR { get; set; }
        public Nullable<int> PROPERTY_TYPE_ID { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public string LOCATION { get; set; }
        public Nullable<int> BEDROOMS { get; set; }
        public Nullable<int> BATHROOMS { get; set; }
        public Nullable<int> FLOORS { get; set; }
        public Nullable<int> GARAGES { get; set; }
        public string AREA { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string BEFORE_PRICE_LABEL { get; set; }
        public string AFTER_PRICE_LABEL { get; set; }
        public string FEATURES { get; set; }
        public string IMG_1 { get; set; }
        public string IMG_2 { get; set; }
        public string IMG_3 { get; set; }
        public string IMG_4 { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public Nullable<int> STATE_ID { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public string POSTAL_CODE { get; set; }
        public string NEIGHBORHOOD { get; set; }
        public Nullable<int> ADDED_BY_ID { get; set; }
        public System.DateTime ADDED_DATE { get; set; }
    
        public virtual CITY CITY { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual USER USER { get; set; }
        public virtual PROPERTY_TYPE PROPERTY_TYPE { get; set; }
        public virtual STATE STATE { get; set; }
        public virtual PROPERTY_STATUS PROPERTY_STATUS { get; set; }
    }
}
