//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateMVC_NOAUTH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.InteropServices;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.PROPERTies = new HashSet<PROPERTY>();
        }
    
        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        [StringLength(255, MinimumLength = 2)]
        public string EMAIL { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        [StringLength(255, MinimumLength = 2)]
        public string PASSWORD { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Full Name")]
        [StringLength(255, MinimumLength = 2)]
        public string FULLNAME { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Mobile")]
        [StringLength(10, MinimumLength = 10)]
        public string MOBILE { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "About Me")]
        [StringLength(1000, MinimumLength = 2)]
        public string ABOUT_ME { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Registration Date")]
        public Nullable<System.DateTime> REGISTRATION_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTY> PROPERTies { get; set; }
        public virtual USER_ROLE USER_ROLE { get; set; }
    }
}
